src/lut/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from posts.views import PostsListView, PostsDetailView, PostsCreateView, PostUpdateView, like

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', PostsListView.as_view()),
    url(r'^posts/(?P<pk>\d+)/$', PostsDetailView.as_view()),
    url(r'^posts/create/$', PostsCreateView.as_view()),
    url(r'^posts/(?P<pk>\d+)/edit/$', PostUpdateView.as_view()),
    url(r'^like/$', like   ),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

src/posts/models.py
from django.db import models
from django.conf import settings


class Posts(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    photo = models.ImageField(blank=True, null=True, upload_to = 'covers/')
    description = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description


class Likes(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    post = models.ForeignKey(Posts, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

src/posts/forms.py
from django import forms

from .models import Posts


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ('photo', 'description')

src/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Posts, Likes
from .forms import PostForm


def like(request):
    post_to_like = Posts.objects.filter(id=request.POST['post_id']).get()
    is_liked = Likes.objects.filter(author=request.user, post_id=post_to_like)

    if not is_liked:
        Likes.objects.create(author=request.user, post=post_to_like)

    return redirect('/')


class PostsListView(ListView):
    model = Posts

    def get_queryset(self):
        return Posts.objects.filter(author=self.request.user)


class PostsDetailView(DetailView):
    model = Posts

    def get_queryset(self):
        return Posts.objects.filter(author=self.request.user)


class PostsCreateView(CreateView):
    form_class = PostForm
    template_name = "form.html"
    success_url = '/'

    def form_valid(self, form):
        obj = form.save(commit=False) # todo что приходит в obj? данный с формы?
        obj.author = self.request.user
        return super(PostsCreateView, self).form_valid(form)


class PostUpdateView(UpdateView):
    form_class = PostForm
    template_name = "form.html"
    success_url = '/'

    def get_queryset(self):
        return Posts.objects.filter(author=self.request.user)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Look Up Table</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css' %}/posts.css">
</head>
<body>
    <header>
        <h1><a href="/">Look Up Table</a></h1>
        <nav>
            <ul>
                <li>Home</li>
                <li>Show</li>
                <li>About</li>
            </ul>
        </nav>
    </header>
    <main>
        {%block content%}{%endblock content%}
    </main>
</body>
</html>

src/templates/form.html
{% extends "base.html" %}

{% block content %}
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    {% if form.instance %}
        {{ form.instance.name }}
    {% endif %}
{% endblock %}

src/templates/posts/posts_detail.html
{% extends "base.html" %}

{% block content %}
        <div>
            <img src="../../media/{{object.photo}}" alt="" style="width: 40vw;">
            {{object.description}}
            {{object.updated}}
        </div>
{% endblock %}

src/templates/posts/posts_list.html
{% extends "base.html" %}

{% block content %}
    <div class="add-button">
        <a href="/posts/create/" class="btn btn-primary"><h1>ADD</h1></a>
    </div>
    <div class="posts-list">
        {% for obj in object_list %}
            <form action="/like/" method="POST"> {% csrf_token %}
                <input type="hidden" name="post_id" value="{{obj.id}}">
                <button type="submit">Like</button>
            </form>
            <p>{{ obj.likes_set.all.count }}</p>
            <a href="posts/{{obj.id}}">
                <div class="list-view">
                    <img src="../media/{{obj.photo}}" alt="">
                    <div class="lv-item-text">
                         {{obj.description}}
                         {{obj.updated}}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}